[build]
  command = "npm run build"
  publish = "build"

[functions]
  node_bundler = "esbuild"
  included_files = ["public/data/knowledge.md"]
  # Ensure environment variables are available in Netlify Functions
  environment = { OPENAI_API_KEY = "${OPENAI_API_KEY}" }

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
